# Generated by Django 3.2.23 on 2023-11-02 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('nickname', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('registration', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('요식업', '요식업'), ('주점', '주점'), ('제조업', '제조업'), ('도소매', '도소메')], max_length=128)),
                ('location', models.TextField()),
            ],
        ),
    ]
