# Generated by Django 3.2.23 on 2023-11-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('요식업', '요식업'), ('주점', '주점'), ('제조업', '제조업'), ('도소매', '도소매')], max_length=128),
        ),
    ]
